# Generated by Django 4.1 on 2022-10-02 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appWebsite", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="image",
            field=models.ImageField(default="null", upload_to=""),
        ),
        migrations.AlterField(
            model_name="article", name="title", field=models.CharField(max_length=110),
        ),
    ]
